services:
  db:
    image: postgres:16
    container_name: trade_db
    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"

    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - 87-0-net

  redis:
    image: redis:8.8
    container_name: redis

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"

    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    networks:
      - 87-0-net

  backend:
    image: archie955/87-0-backend:latest
    container_name: 87-0-backend

    logging:
      driver: json-file
      options:
        max-size: "300m"
        max-file: "5"
        compress: "true"

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - db
      - redis

    environment:
      POSTGRES_HOSTNAME: db

    command: >
      sh -c "uv run alembic upgrade head &&
             uv run uvicorn main:app --host 0.0.0.0 --port 8000"

    networks:
      - 87-0-net

  frontend:
    image: archie955/87-0-frontend:latest
    container_name: 87-0-frontend

    logging:
      driver: json-file
      options:
        max-size: "150m"
        max-file: "5"
        compress: "true"

    restart: unless-stopped

    depends_on:
      - backend

    networks:
      - 87-0-net

  caddy:
    image: caddy:2

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"


    container_name: 87-0-caddy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - frontend
      - backend

    networks:
      - 87-0-net

networks:
  87-0-net:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config: