# pyrefly: ignore-errors[bad-argument-type]

"""add selectin loading

Revision ID: 634dd1285ec9
Revises: efa5b5610486
Create Date: 2026-09-01 11:35:59.273588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634dd1285ec9'
down_revision: Union[str, Sequence[str], None] = 'efa5b5610486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'player', ['name'])
    op.drop_constraint(op.f('player_team_id_fkey'), 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(op.f('player_team_id_fkey'), 'player', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'player', type_='unique')
    op.alter_column('email', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
