"""data versioning

Revision ID: 77876269e261
Revises: 1896e61b5758
Create Date: 2026-09-18 15:10:45.734301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77876269e261'
down_revision: Union[str, Sequence[str], None] = '1896e61b5758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_version',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.add_column('email', sa.Column('attempts', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('email', sa.Column('lockout', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('steam', 'steam_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=17),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steam', 'steam_id',
               existing_type=sa.String(length=17),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('email', 'lockout')
    op.drop_column('email', 'attempts')
    op.drop_table('data_version')
    # ### end Alembic commands ###
