import numpy as np

from models.enums import Roles


def mock_igl_bonus(p) -> float:
    perf_sum = (4 * p["wins"] + 3 * p["second"] + 2 * p["semi"] + p["quarter"]) / 40
    perf = (
        perf_sum / np.sqrt(p["total_tournaments"])
        if p["total_tournaments"] > 0
        else 0.0
    )
    team_bonus = np.sqrt(p["win_teammates"]) / 10
    return perf + team_bonus


data = {
    "teams": [
        {"name": "Falcons"},
        {"name": "Vitality"},
    ],
    "players": [
        {
            "name": "NiKo",
            "team_name": "Falcons",
            "role": Roles.CLOSER,
            "hltv": 1.22,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "m0nesy",
            "team_name": "Falcons",
            "role": Roles.AWPER,
            "hltv": 1.27,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "TeSeS",
            "team_name": "Falcons",
            "role": Roles.SUPPORT,
            "hltv": 1.02,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "kyousuke",
            "team_name": "Falcons",
            "role": Roles.OPENER,
            "hltv": 1.16,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "karrigan",
            "team_name": "Falcons",
            "role": Roles.OPENER,
            "hltv": 0.82,
            "majors": 2,
            "wins": 22,
            "second": 16,
            "semi": 44,
            "quarter": 37,
            "total_tournaments": 122,
            "major_teammates": 8,
            "win_teammates": 18,
        },
        {
            "name": "ZywOo",
            "team_name": "Vitality",
            "role": Roles.AWPER,
            "hltv": 1.34,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "ropz",
            "team_name": "Vitality",
            "role": Roles.CLOSER,
            "hltv": 1.14,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "mezii",
            "team_name": "Vitality",
            "role": Roles.SUPPORT,
            "hltv": 1.06,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "flameZ",
            "team_name": "Vitality",
            "role": Roles.OPENER,
            "hltv": 1.11,
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "apEX",
            "team_name": "Vitality",
            "role": Roles.OPENER,
            "hltv": 0.98,
            "majors": 3,
            "wins": 28,
            "second": 7,
            "semi": 8,
            "quarter": 3,
            "total_tournaments": 61,
            "major_teammates": 8,
            "win_teammates": 9,
        },
    ],
}
