from models.enums import Roles


def mock_scores(igl: float, hltv: float):
    return {"hltv": hltv, "igl_score": igl, "odds": hltv**2 - 1, "igl_odds": igl**2 - 1}


data = {
    "teams": [{"name": "Falcons"}, {"name": "Vitality"}, {"name": "Spirit"}],
    "players": [
        {
            "name": "NiKo",
            "team_name": "Falcons",
            "role": Roles.CLOSER,
            **mock_scores(1.02, 1.22),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "m0nesy",
            "team_name": "Falcons",
            "role": Roles.AWPER,
            **mock_scores(1.07, 1.27),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "TeSeS",
            "team_name": "Falcons",
            "role": Roles.SUPPORT,
            **mock_scores(0.86, 1.02),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "kyousuke",
            "team_name": "Falcons",
            "role": Roles.OPENER,
            **mock_scores(0.96, 1.16),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "karrigan",
            "team_name": "Falcons",
            "role": Roles.OPENER,
            **mock_scores(1.30, 0.78),
            "majors": 2,
            "wins": 22,
            "second": 16,
            "semi": 44,
            "quarter": 37,
            "total_tournaments": 122,
            "major_teammates": 8,
            "win_teammates": 18,
        },
        {
            "name": "ZywOo",
            "team_name": "Vitality",
            "role": Roles.AWPER,
            **mock_scores(1.09, 1.34),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "ropz",
            "team_name": "Vitality",
            "role": Roles.CLOSER,
            **mock_scores(0.94, 1.14),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "mezii",
            "team_name": "Vitality",
            "role": Roles.SUPPORT,
            **mock_scores(0.90, 1.06),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "flameZ",
            "team_name": "Vitality",
            "role": Roles.OPENER,
            **mock_scores(0.91, 1.11),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "apEX",
            "team_name": "Vitality",
            "role": Roles.OPENER,
            **mock_scores(1.29, 0.98),
            "majors": 3,
            "wins": 28,
            "second": 7,
            "semi": 8,
            "quarter": 3,
            "total_tournaments": 61,
            "major_teammates": 8,
            "win_teammates": 9,
        },
        {
            "name": "donk",
            "team_name": "Spirit",
            "role": Roles.OPENER,
            **mock_scores(1.16, 1.4),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "TN1R",
            "team_name": "Spirit",
            "role": Roles.CLOSER,
            **mock_scores(0.88, 1.07),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "magixx",
            "team_name": "Spirit",
            "role": Roles.OPENER,
            **mock_scores(1.16, 1.02),
            "majors": 0,
            "wins": 7,
            "second": 2,
            "semi": 2,
            "quarter": 0,
            "total_tournaments": 11,
            "major_teammates": 0,
            "win_teammates": 4,
        },
        {
            "name": "zont1x",
            "team_name": "Spirit",
            "role": Roles.SUPPORT,
            **mock_scores(0.80, 0.98),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
        {
            "name": "sh1ro",
            "team_name": "Spirit",
            "role": Roles.AWPER,
            **mock_scores(0.97, 1.16),
            "majors": 0,
            "wins": 0,
            "second": 0,
            "semi": 0,
            "quarter": 0,
            "total_tournaments": 0,
            "major_teammates": 0,
            "win_teammates": 0,
        },
    ],
}
